<?php

/**
 * @file
 * Contains theme_swicher.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function theme_swicher_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the theme_swicher module.
    case 'help.page.theme_swicher':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Switches the active theme base on Role') . '</p>';
      return $output;

    default:
  }
}
